language: csharp
solution: ZConfig.NET.sln
mono: none
dotnet: 2.1
before_install:
        - cd ZConfig.NET
install:
        - dotnet restore
script:
        - dotnet build 
        - dotnet test TestLiZConfigCommon\TestLiZConfigCommon.csproj
