language: csharp
solution: ZConfig.NET.sln
mono: none
dist: xenial
dotnet: 2.2
before_install:
        - cd ZConfig.NET
install:
        - dotnet restore
script:
        - dotnet build 
        - dotnet test TestLiZConfigCommon/TestLibZConfigCommon.csproj
global:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
          DOTNET_CLI_TELEMTERY_OUTPUT=1

